## 1. Load packages

In [54]:
# data processing packages
import numpy as np
from numpy import random
import pandas as pd
import re

# machine learning packages
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn import metrics
from sklearn.decomposition import PCA

# visualization packages
import seaborn as sb
import matplotlib.pyplot as plt

# other packages
import torch
from pathlib import Path
import random
import itertools

## 2. Read the files

In [55]:
## Create the necessary folders
Path('./Figures/').mkdir(parents=True, exist_ok=True)
Path('./Results/').mkdir(parents=True, exist_ok=True)

In [56]:
## Set path to the data set
dataset_path = "./dataset/77_cancer_proteomes_CPTAC_itraq.csv"
clinical_info = "./dataset/clinical_data_breast_cancer.csv"
pam50_proteins = "./dataset/PAM50_proteins.csv"

## Load data
data = pd.read_csv(dataset_path,header=0,index_col=0)
clinical_file = pd.read_csv(clinical_info,header=0,index_col=0) ## holds clinical information about each patient/sample
pam50 = pd.read_csv(pam50_proteins,header=0)

# RefSeq protein ID (each protein has a unique ID in a RefSeq database)
print(data.index.name)
data.head()

RefSeq_accession_number

,gene_symbol,gene_name,AO-A12D.01TCGA,C8-A131.01TCGA,AO-A12B.01TCGA,BH-A18Q.02TCGA,C8-A130.02TCGA,C8-A138.03TCGA,E2-A154.03TCGA,C8-A12L.04TCGA,...,AO-A12B.34TCGA,A2-A0SW.35TCGA,AO-A0JL.35TCGA,BH-A0BV.35TCGA,A2-A0YM.36TCGA,BH-A0C7.36TCGA,A2-A0SX.36TCGA,263d3f-I.CPTAC,blcdb9-I.CPTAC,c4155b-C.CPTAC
RefSeq_accession_number,,,,,,,,,,,,,,,,,,,,,
NP_958782,PLEC,plectin isoform 1,1.096131,2.609943,-0.659828,0.195341,-0.494060,2.765081,0.862659,1.407570,...,-0.963904,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.398560,0.598585,-0.191285,0.566975
NP_958785,NaN,plectin isoform 1g,1.111370,2.650422,-0.648742,0.215413,-0.503899,2.779709,0.870186,1.407570,...,-0.938210,-0.487772,-0.10668,-0.055893,0.658143,-0.547749,-0.392601,0.606697,-0.183918,0.578702
NP_958786,PLEC,plectin isoform 1a,1.111370,2.650422,-0.654285,0.215413,-0.500619,2.779709,0.870186,1.410312,...,-0.943919,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
NP_000436,NaN,plectin isoform 1c,1.107561,2.646374,-0.632113,0.205377,-0.510459,2.797995,0.866423,1.407570,...,-0.935355,-0.487772,-0.10668,-0.055893,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
NP_958781,NaN,plectin isoform 1e,1.115180,2.646374,-0.640428,0.215413,-0.503899,2.787023,0.870186,1.413053,...,-0.935355,-0.503853,-0.10668,-0.062523,0.651264,-0.556675,-0.395581,0.603993,-0.167079,0.576747

## 3. Data Set Processing

In [57]:
## Drop unused information columns
data.drop(['gene_symbol','gene_name'],axis=1,inplace=True)

## Change the protein data sample names to a format matching the clinical data set
data.rename(columns=lambda x: "TCGA-%s" % (re.split('[_|-|.]',x)[0]) if bool(re.search("TCGA",x)) is True else x,inplace=True)

data.head()

,TCGA-AO-A12D,TCGA-C8-A131,TCGA-AO-A12B,TCGA-BH-A18Q,TCGA-C8-A130,TCGA-C8-A138,TCGA-E2-A154,TCGA-C8-A12L,TCGA-A2-A0EX,TCGA-AO-A12D,...,TCGA-AO-A12B,TCGA-A2-A0SW,TCGA-AO-A0JL,TCGA-BH-A0BV,TCGA-A2-A0YM,TCGA-BH-A0C7,TCGA-A2-A0SX,263d3f-I.CPTAC,blcdb9-I.CPTAC,c4155b-C.CPTAC
RefSeq_accession_number,,,,,,,,,,,,,,,,,,,,,
NP_958782,1.096131,2.609943,-0.659828,0.195341,-0.494060,2.765081,0.862659,1.407570,1.185108,1.100688,...,-0.963904,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.398560,0.598585,-0.191285,0.566975
NP_958785,1.111370,2.650422,-0.648742,0.215413,-0.503899,2.779709,0.870186,1.407570,1.192612,1.100688,...,-0.938210,-0.487772,-0.10668,-0.055893,0.658143,-0.547749,-0.392601,0.606697,-0.183918,0.578702
NP_958786,1.111370,2.650422,-0.654285,0.215413,-0.500619,2.779709,0.870186,1.410312,1.188860,1.100688,...,-0.943919,-0.487772,-0.10668,-0.065838,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
NP_000436,1.107561,2.646374,-0.632113,0.205377,-0.510459,2.797995,0.866423,1.407570,1.185108,1.100688,...,-0.935355,-0.487772,-0.10668,-0.055893,0.655850,-0.552212,-0.392601,0.603993,-0.186022,0.576747
NP_958781,1.115180,2.646374,-0.640428,0.215413,-0.503899,2.787023,0.870186,1.413053,1.200116,1.093358,...,-0.935355,-0.503853,-0.10668,-0.062523,0.651264,-0.556675,-0.395581,0.603993,-0.167079,0.576747

In [58]:
## Transpose data for the clustering algorithm since we want to divide patient samples, not proteins
print(data.shape)
datat = data.transpose()
print(datat.shape)

datat.head()

(12553, 83)
(83, 12553)

RefSeq_accession_number,NP_958782,NP_958785,NP_958786,NP_000436,NP_958781,NP_958780,NP_958783,NP_958784,NP_112598,NP_001611,...,NP_001193600,NP_061134,NP_932347,NP_003593,NP_997203,NP_001191293,NP_775791,NP_004065,NP_068752,NP_219494
TCGA-AO-A12D,1.096131,1.111370,1.111370,1.107561,1.115180,1.107561,1.111370,1.111370,-1.517390,0.482754,...,NaN,NaN,NaN,-0.340163,NaN,NaN,NaN,NaN,-0.633517,12.666488
TCGA-C8-A131,2.609943,2.650422,2.650422,2.646374,2.646374,2.646374,2.650422,2.650422,3.909313,-1.045294,...,NaN,NaN,NaN,3.451902,NaN,NaN,NaN,NaN,4.840325,0.140736
TCGA-AO-A12B,-0.659828,-0.648742,-0.654285,-0.632113,-0.640428,-0.654285,-0.648742,-0.648742,-0.618256,1.222003,...,NaN,NaN,NaN,-1.718531,NaN,NaN,NaN,NaN,-1.965192,-2.854835
TCGA-BH-A18Q,0.195341,0.215413,0.215413,0.205377,0.215413,0.215413,0.215413,0.215413,-1.035760,-0.517226,...,0.048144,NaN,-0.881872,2.527072,-8.111243,-16.029761,-2.046065,-1.778435,NaN,-3.069752
TCGA-C8-A130,-0.494060,-0.503899,-0.500619,-0.510459,-0.503899,-0.503899,-0.500619,-0.500619,-1.845366,-0.405503,...,1.457462,NaN,1.710012,0.296389,-1.753529,1.729692,-0.425182,-0.149673,NaN,-0.047997

In [59]:
print("Number of patients in clinical data set: ", len(clinical_file.index))
print("Number of patients in protein data set: ", len(datat.index))

Number of patients in clinical data set:  105
Number of patients in protein data set:  83

In [60]:
## Drop clinical entries for samples not in our protein data set
clinical = clinical_file.loc[[x for x in clinical_file.index.tolist() if x in datat.index],:]

print("The shape of the clinical data set: ", clinical.shape)
clinical.head()

The shape of the clinical data set:  (77, 29)

,Gender,Age at Initial Pathologic Diagnosis,ER Status,PR Status,HER2 Final Status,Tumor,Tumor--T1 Coded,Node,Node-Coded,Metastasis,...,PAM50 mRNA,SigClust Unsupervised mRNA,SigClust Intrinsic mRNA,miRNA Clusters,methylation Clusters,RPPA Clusters,CN Clusters,Integrated Clusters (with PAM50),Integrated Clusters (no exp),Integrated Clusters (unsup exp)
Complete TCGA ID,,,,,,,,,,,,,,,,,,,,,
TCGA-A2-A0CM,FEMALE,40,Negative,Negative,Negative,T2,T_Other,N0,Negative,M0,...,Basal-like,-12,-13,4,4,Basal,4,2,1,1
TCGA-BH-A18Q,FEMALE,56,Negative,Negative,Negative,T2,T_Other,N1,Positive,M0,...,Basal-like,-12,-13,5,5,Basal,1,2,2,2
TCGA-A7-A0CE,FEMALE,57,Negative,Negative,Negative,T2,T_Other,N0,Negative,M0,...,Basal-like,0,-13,5,5,Basal,1,2,2,2
TCGA-D8-A142,FEMALE,74,Negative,Negative,Negative,T3,T_Other,N0,Negative,M0,...,Basal-like,0,-13,3,5,X,1,2,2,2
TCGA-AO-A0J6,FEMALE,61,Negative,Negative,Negative,T2,T_Other,N0,Negative,M0,...,Basal-like,-12,-13,2,5,Basal,1,2,2,2

In [61]:
## Add clinical meta data to our protein data set, note: all numerical features for analysis start with NP_ or XP_
merged = datat.merge(clinical,left_index=True,right_index=True)

# Drop the duplicated columns (added by Pietro Gavazzi)
liste = merged.index.copy()
liste = list(liste)

for i in np.unique(merged.index):
    liste.remove(i)

## Change name to make it look nicer in the code!
processed = merged.drop(np.unique(liste))

print("Shape of the merged data set: ", processed.shape)
print("with %d patients and %d features" % (processed.shape[0], processed.shape[1]))

processed.head()

Shape of the merged data set:  (74, 12582)
with 74 patients and 12582 features

,NP_958782,NP_958785,NP_958786,NP_000436,NP_958781,NP_958780,NP_958783,NP_958784,NP_112598,NP_001611,...,PAM50 mRNA,SigClust Unsupervised mRNA,SigClust Intrinsic mRNA,miRNA Clusters,methylation Clusters,RPPA Clusters,CN Clusters,Integrated Clusters (with PAM50),Integrated Clusters (no exp),Integrated Clusters (unsup exp)
TCGA-A2-A0CM,0.683404,0.694424,0.698098,0.687077,0.687077,0.698098,0.698098,0.698098,-2.652150,-0.984373,...,Basal-like,-12,-13,4,4,Basal,4,2,1,1
TCGA-A2-A0D2,0.107491,0.104164,0.107491,0.097512,0.104164,0.104164,0.104164,0.104164,-0.880454,-1.512473,...,Basal-like,-12,-13,4,5,Basal,3,2,2,2
TCGA-A2-A0EQ,-0.912670,-0.927979,-0.927979,-0.931806,-0.927979,-0.927979,-0.927979,-0.927979,-3.071151,-2.278943,...,HER2-enriched,-5,-2,5,4,Basal,4,4,1,1
TCGA-A2-A0EV,0.452986,0.472590,0.472590,0.458587,0.472590,0.472590,0.472590,0.472590,-0.742871,1.811277,...,Luminal A,-4,0,4,2,ReacI,3,3,3,4
TCGA-A2-A0EX,1.185108,1.192612,1.188860,1.185108,1.200116,1.188860,1.188860,1.192612,1.046289,2.138081,...,Luminal A,-7,-5,4,4,ReacI,4,3,1,4

In [62]:
## Numerical data for the algorithm, NP_xx/XP_xx are protein identifiers from RefSeq database
X = processed.loc[:,[x for x in processed.columns if bool(re.search("NP_|XP_|YP_",x)) == True]]
Y = pd.get_dummies(processed.drop(X.columns, axis=1)['Integrated Clusters (with PAM50)'], prefix="PAM50")

## Select only the PAM50 proteins - known panel of genes used for breast cancer subtype prediction
# processed_numerical_p50 = processed_numerical.iloc[:,processed_numerical.columns.isin(pam50['RefSeqProteinID'])]
# processed_numerical_p50.head()

X.columns

Index(['NP_958782', 'NP_958785', 'NP_958786', 'NP_000436', 'NP_958781',
       'NP_958780', 'NP_958783', 'NP_958784', 'NP_112598', 'NP_001611',
       ...
       'NP_001193600', 'NP_061134', 'NP_932347', 'NP_003593', 'NP_997203',
       'NP_001191293', 'NP_775791', 'NP_004065', 'NP_068752', 'NP_219494'],
      dtype='object', length=12553)

In [63]:
Y.head()

              PAM50_1  PAM50_2  PAM50_3  PAM50_4
TCGA-A2-A0CM        0        1        0        0
TCGA-A2-A0D2        0        1        0        0
TCGA-A2-A0EQ        0        0        0        1
TCGA-A2-A0EV        0        0        1        0
TCGA-A2-A0EX        0        0        1        0

In [64]:
# Save the data
torch.save(X, './Results/X')
torch.save(Y, './Results/Y')

KeyboardInterrupt:

## 3. Data Engineering

In [ ]:
# Read the processed data set
X = torch.load('./Results/X')
Y = torch.load('./Results/Y')

In [ ]:
X.head()

,NP_958782,NP_958785,NP_958786,NP_000436,NP_958781,NP_958780,NP_958783,NP_958784,NP_112598,NP_001611,...,NP_001193600,NP_061134,NP_932347,NP_003593,NP_997203,NP_001191293,NP_775791,NP_004065,NP_068752,NP_219494
TCGA-A2-A0CM,0.683404,0.694424,0.698098,0.687077,0.687077,0.698098,0.698098,0.698098,-2.652150,-0.984373,...,NaN,NaN,1.153614,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCGA-A2-A0D2,0.107491,0.104164,0.107491,0.097512,0.104164,0.104164,0.104164,0.104164,-0.880454,-1.512473,...,0.919136,-1.648856,0.832649,NaN,-8.324969,-4.679219,NaN,-1.106650,NaN,-6.941181
TCGA-A2-A0EQ,-0.912670,-0.927979,-0.927979,-0.931806,-0.927979,-0.927979,-0.927979,-0.927979,-3.071151,-2.278943,...,-0.801685,NaN,NaN,3.802310,-6.373934,-1.123160,NaN,NaN,NaN,NaN
TCGA-A2-A0EV,0.452986,0.472590,0.472590,0.458587,0.472590,0.472590,0.472590,0.472590,-0.742871,1.811277,...,-4.966177,-1.471027,NaN,-0.474013,-12.278546,-10.337729,-0.653251,NaN,NaN,NaN
TCGA-A2-A0EX,1.185108,1.192612,1.188860,1.185108,1.200116,1.188860,1.188860,1.192612,1.046289,2.138081,...,1.451490,-2.018981,0.877456,NaN,NaN,-6.101005,NaN,-1.726336,NaN,NaN

In [ ]:
Y.head()

              PAM50_1  PAM50_2  PAM50_3  PAM50_4
TCGA-A2-A0CM        0        1        0        0
TCGA-A2-A0D2        0        1        0        0
TCGA-A2-A0EQ        0        0        0        1
TCGA-A2-A0EV        0        0        1        0
TCGA-A2-A0EX        0        0        1        0

### 3.1 Missing value process
We drop all the columns with nan values

In [ ]:
nan_counts = np.sum(X.isna(), axis=0)
col_to_drop = nan_counts[nan_counts != 0].index
X.drop(col_to_drop, axis=1, inplace=True)

In [ ]:
X.shape

(74, 8023)

### 3.2 Data Scaling
We use the standardization for each feature of the data set

In [ ]:
col_names = X.columns
idx = X.index
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=col_names, index=idx)
X_scaled.shape

(74, 8023)

## 4. Basic model

### 4.1 K-Means model

In [ ]:
kmeans = KMeans(n_clusters=4, algorithm='full').fit(X_scaled)
pred0 = kmeans.labels_

c:\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:1318: FutureWarning: algorithm='full' is deprecated, it will be removed in 1.3. Using 'lloyd' instead.
  warnings.warn(

### 4.2 Evaluation Metric

In [ ]:

# https://medium.com/data-science-in-your-pocket/calculating-precision-recall-for-multi-class-classification-9055931ee229 


permutation_matrices = []
for i in itertools.permutations([0, 1, 2, 3]):
    matrix = np.zeros((4, 4))
    for j in range(len(matrix)):
        matrix[j][i[j]] = 1

    permutation_matrices.append(matrix)



def get_dataframe(y_array_pred, y_true):
    pred = pd.DataFrame(pd.get_dummies(y_array_pred))
    pred.columns = ['cluster_' + str(x) for x in range(1, 5)]
    pred = pred.set_index(y_true.index)
    return(pred)



def calculate_mean_prec(matrix):
    matrix = np.array(matrix)
    assert(matrix.shape[0]==matrix.shape[1]), f"matrix must be squared, same number of true labels {matrix.shape[0]} as predicted{matrix.shape[1]}"

    prec = np.zeros(len(matrix))

    for i in range(len(matrix)):
        true_pos_classified_pos = matrix[i][i]
        classified_pos= np.sum(matrix[i])
        prec[i] = true_pos_classified_pos/classified_pos
    
    return np.mean(prec)

def calculate_mean_recall(matrix):
    matrix = np.array(matrix)
    assert(matrix.shape[0]==matrix.shape[1]), f"matrix must be squared, same number of true labels {matrix.shape[0]} as predicted{matrix.shape[1]}"

    rec = np.zeros(len(matrix.T))

    for i in range(len(matrix.T)):
        true_pos_classified_pos = matrix.T[i][i]
        true_pos= np.sum(matrix.T[i])
        rec[i] = true_pos_classified_pos/true_pos

    return np.mean(rec)


def model_eval(y_true, y_pred):

    length = len(y_true.T)
    assert (y_pred.shape==y_true.shape), f"expected same shape of colums for both y_true: {y_true.shape} and y_pred {y_pred.shape}"
    
    matrix = np.zeros((length, length))

    indi = 0
    for i in y_pred.T.index:
        indj = 0
        for j in y_true.T.index:
            matrix[indi][indj] += np.array(y_pred[i]) @ np.array(y_true[j])
            indj+=1
        indi+=1

    
    matrix = pd.DataFrame(matrix, columns=y_true.T.index, index=y_pred.T.index)


    best_perm = None
    best_Fscore = 0

    ## version 3.0
    for permu_mat in permutation_matrices:
        M = permu_mat@matrix

        prec = calculate_mean_prec(M)
        rec = calculate_mean_recall(M)

        Fscore = 2/(1/prec + 1/rec)
        
        if Fscore>best_Fscore:
            best_perm = permu_mat
            best_Fscore = Fscore
    
    new_matrix = best_perm@matrix

    indexes = []
    for i in range(len(best_perm)):
        for j in range(len(best_perm)):
            if best_perm[i][j]==1:
                indexes.append(matrix.index[j])


    new_matrix.index = indexes

    return new_matrix, best_Fscore

In [ ]:
y_pred = get_dataframe(pred0, Y)
new_matrix, best_Fscore = model_eval(Y, y_pred)
new_matrix

           PAM50_1  PAM50_2  PAM50_3  PAM50_4
cluster_1      4.0      0.0      1.0      3.0
cluster_3      4.0      9.0      3.0      6.0
cluster_4      0.0      4.0     13.0      3.0
cluster_2      2.0      5.0      6.0     11.0

In [ ]:
best_Fscore

0.4949402509708698

## 5. Model improvement

### 5.1 Feature selection

In [65]:
Fscor_list = []
max_Fscore = 0
feature_selected = None

for i in range(X_scaled.shape[1]):
    print(i)
    print(X_scaled.shape[1])
    X_reduced = np.array(X_scaled.iloc[:, i]).reshape(-1, 1)
    k_means = KMeans(n_clusters=4).fit(X_reduced)
    pred_ = k_means.labels_
    y_pred_ = get_dataframe(pred_, Y)
    _, Fscore = model_eval(Y, y_pred_)
    Fscor_list.append(Fscore)

    if Fscore > max_Fscore:
        max_Fscore = Fscore
        feature_selected = X_scaled.columns[i]

print(max_Fscore)
print(feature_selected)

0
501
1
501
2
501
3
501
4
501
5
501
6
501
7
501
8
501
9
501
10
501
11
501
12
501
13
501
14
501
15
501
16
501
17
501
18
501
19
501
20
501
21
501
22
501
23
501
24
501
25
501
26
501
27
501
28
501
29
501
30
501
31
501
32
501
33
501
34
501
35
501
36
501
37
501
38
501
39
501
40
501
41
501
42
501
43
501
44
501
45
501
46
501
47
501
48
501
49
501
50
501
51
501
52
501
53
501
54
501
55
501
56
501
57
501
58
501
59
501
60
501
61
501
62
501
63
501
64
501
65
501
66
501
67
501
68
501
69
501
70
501
71
501
72
501
73
501
74
501
75
501
76
501
77
501
78
501
79
501
80
501
81
501
82
501
83
501
84
501
85
501
86
501
87
501
88
501
89
501
90
501
91
501
92
501
93
501
94
501
95
501
96
501
97
501
98
501
99
501
100
501
101
501
102
501
103
501
104
501
105
501
106
501
107
501
108
501
109
501
110
501
111
501
112
501
113
501
114
501
115
501
116
501
117
501
118
501
119
501
120
501
121
501
122
501
123
501
124
501
125
501
126
501
127
501
128
501
129
501
130
501
131
501
132
501
133
501
134
501
135
501
136
501
137
501
138
501
139
501
140
501
141
501
142
501
143
501
144
501
145
501
146
501
147
501
148
501
149
501
150
501
151
501
152
501
153
501
154
501
155
501
156
501
157
501
158
501
159
501
160
501
161
501
162
501
163
501
164
501
165
501
166
501
167
501
168
501
169
501
170
501
171
501
172
501
173
501
174
501
175
501
176
501
177
501
178
501
179
501
180
501
181
501
182
501
183
501
184
501
185
501
186
501
187
501
188
501
189
501
190
501
191
501
192
501
193
501
194
501
195
501
196
501
197
501
198
501
199
501
200
501
201
501
202
501
203
501
204
501
205
501
206
501
207
501
208
501
209
501
210
501
211
501
212
501
213
501
214
501
215
501
216
501
217
501
218
501
219
501
220
501
221
501
222
501
223
501
224
501
225
501
226
501
227
501
228
501
229
501
230
501
231
501
232
501
233
501
234
501
235
501
236
501
237
501
238
501
239
501
240
501
241
501
242
501
243
501
244
501
245
501
246
501
247
501
248
501
249
501
250
501
251
501
252
501
253
501
254
501
255
501
256
501
257
501
258
501
259
501
260
501
261
501
262
501
263
501
264
501
265
501
266
501
267
501
268
501
269
501
270
501
271
501
272
501
273
501
274
501
275
501
276
501
277
501
278
501
279
501
280
501
281
501
282
501
283
501
284
501
285
501
286
501
287
501
288
501
289
501
290
501
291
501
292
501
293
501
294
501
295
501
296
501
297
501
298
501
299
501
300
501
301
501
302
501
303
501
304
501
305
501
306
501
307
501
308
501
309
501
310
501
311
501
312
501
313
501
314
501
315
501
316
501
317
501
318
501
319
501
320
501
321
501
322
501
323
501
324
501
325
501
326
501
327
501
328
501
329
501
330
501
331
501
332
501
333
501
334
501
335
501
336
501
337
501
338
501
339
501
340
501
341
501
342
501
343
501
344
501
345
501
346
501
347
501
348
501
349
501
350
501
351
501
352
501
353
501
354
501
355
501
356
501
357
501
358
501
359
501
360
501
361
501
362
501
363
501
364
501
365
501
366
501
367
501
368
501
369
501
370
501
371
501
372
501
373
501
374
501
375
501
376
501
377
501
378
501
379
501
380
501
381
501
382
501
383
501
384
501
385
501
386
501
387
501
388
501
389
501
390
501
391
501
392
501
393
501
394
501
395
501
396
501
397
501
398
501
399
501
400
501
401
501
402
501
403
501
404
501
405
501
406
501
407
501
408
501
409
501
410
501
411
501
412
501
413
501
414
501
415
501
416
501
417
501
418
501
419
501
420
501
421
501
422
501
423
501
424
501
425
501
426
501
427
501
428
501
429
501
430
501
431
501
432
501
433
501
434
501
435
501
436
501
437
501
438
501
439
501
440
501
441
501
442
501
443
501
444
501
445
501
446
501
447
501
448
501
449
501
450
501
451
501
452
501
453
501
454
501
455
501
456
501
457
501
458
501
459
501
460
501
461
501
462
501
463
501
464
501
465
501
466
501
467
501
468
501
469
501
470
501
471
501
472
501
473
501
474
501
475
501
476
501
477
501
478
501
479
501
480
501
481
501
482
501
483
501
484
501
485
501
486
501
487
501
488
501
489
501
490
501
491
501
492
501
493
501
494
501
495
501
496
501
497
501
498
501
499
501
500
501
0.5023116440802425
NP_004332

In [67]:
X_reduced = np.array(X_scaled[feature_selected]).reshape(-1, 1)
k_means = KMeans(n_clusters=4).fit(X_reduced)
pred = k_means.labels_
y_pred = get_dataframe(pred, Y)
error = model_eval(Y, y_pred)

           PAM50_1  PAM50_2  PAM50_3  PAM50_4
cluster_1      8.0      3.0     11.0      8.0
cluster_3      1.0      7.0      1.0      1.0
cluster_2      0.0      1.0      4.0      1.0
cluster_4      1.0      7.0      7.0     13.0

### 5.2 Random Dataset